// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    blogbody: string;
    blogcontainer: string;
    blogcover: string;
    blogsubtitle: string;
    blogtitle: string;
    inline: string;
    inlineImage: string;
    inlineImageContainer: string;
    inlineImageTitle: string;
    loadingBody: string;
    loadingPlaceholder: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
