const netlifyPlugin = require("preact-cli-plugin-netlify");
const ImageminPlugin = require("imagemin-webpack-plugin").default;
const imageminMozjpeg = require("imagemin-mozjpeg");
import { resolve } from "path";

module.exports = (config, env) => {
  config.module.rules[4].use.splice(1, 0, {
    loader: "@teamsupercell/typings-for-css-modules-loader",
    options: {
      banner:
        "// This file is automatically generated from your CSS. Any edits will be overwritten.",
      disableLocalsExport: true,
    },
  });
  // Use any `index` file, not just index.js
  config.resolve.alias["preact-cli-entrypoint"] = resolve(
    process.cwd(),
    "src",
    "index"
  );
  netlifyPlugin(config);

  env.production &&
    !env.ssr &&
    config.plugins.push(
      new ImageminPlugin({
        from: "./build/assets/**",
        pngquant: {
          quality: "60",
        },
        plugins: [
          imageminMozjpeg({
            quality: 50,
            progressive: true,
          }),
        ],
      })
    );
  return config;
};
