// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    blogtitle: string;
    loadingBody: string;
    loadingPlaceholder: string;
    pageBlogs: string;
    pageTitle: string;
    preview: string;
    tag: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
